# Generated by Django 5.1.6 on 2025-04-25 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustComProj', '0004_recommendationtest_userguide_profile_has_seen_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='has_seen_guide',
            field=models.BooleanField(default=False, verbose_name='Просмотрено руководство'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
