# Generated by Django 5.1.6 on 2025-05-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustComProj', '0005_alter_profile_has_seen_guide_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
