from django.urls import path
from . import views

urlpatterns = [
    # HR-панель и связанные маршруты
    path('dashboard/hr/', views.hr_dashboard, name='hr_dashboard'),
    path('dashboard/hr/manage_employees/', views.manage_employees, name='manage_employees'),
    path('dashboard/hr/assign_courses/', views.assign_courses, name='assign_courses'),
    path('dashboard/hr/track_performance/', views.track_performance, name='track_performance'),
    path('dashboard/hr/evaluate_training/', views.evaluate_training, name='evaluate_training'),
    path('dashboard/hr/view_requests/', views.hr_view_requests, name='hr_view_requests'),
    
    # Основные маршруты
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/redirect/', views.dashboard_redirect, name='dashboard_redirect'),
    path('courses/', views.courses_list, name='courses_list'),
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),
    path('course/<int:course_id>/lectures/', views.course_lectures, name='course_lectures'),
    path('lecture/<int:lecture_id>/', views.lecture_detail, name='lecture_detail'),
    path('course/<int:course_id>/add_lecture/', views.add_lecture, name='add_lecture'),
    path('lecture/<int:lecture_id>/edit/', views.edit_lecture, name='edit_lecture'),
    path('lecture/<int:lecture_id>/delete/', views.delete_lecture, name='delete_lecture'),
    path('lecture/<int:lecture_id>/mark_complete/', views.mark_lecture_complete, name='mark_lecture_complete'),
    path('course/<int:course_id>/enroll/', views.enroll_course, name='enroll_course'),
    path('lecture/<int:lecture_id>/test/<int:test_id>/', views.lecture_test, name='lecture_test'),
    path('lecture/<int:lecture_id>/add_test/', views.add_test, name='add_test'),
    path('test/<int:test_id>/add_question/', views.add_question, name='add_question'),
    path('question/<int:question_id>/add_answer/', views.add_answer, name='add_answer'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/employee/', views.employee_dashboard, name='employee_dashboard'),
    path('dashboard/teacher/', views.teacher_dashboard, name='teacher_dashboard'),
    path('dashboard/training_manager/', views.training_manager_dashboard, name='training_manager_dashboard'),
    path('add-lecture-material/', views.add_lecture_material, name='add_lecture_material'),
    path('create-course/', views.create_course, name='create_course'),
    path('course/<int:course_id>/edit/', views.edit_course, name='edit_course'),
    path('course/<int:course_id>/delete/', views.delete_course, name='delete_course'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/training-manager/', views.training_manager_dashboard, name='training_manager_dashboard'),
    path('answer-questions/', views.answer_questions, name='answer_questions'),
    path('hr/dashboard/', views.hr_dashboard, name='hr_dashboard'),
    path('training-manager/create-plan/', views.create_training_plan, name='create_training_plan'),
    path('training-manager/review-requests/', views.review_requests, name='review_requests'),
    path('training-manager/test-difficulty/', views.test_difficulty, name='test_difficulty'),
    path('employee/my-requests/', views.my_requests, name='my_requests'),
    path('recommendation-test/', views.recommendation_test, name='recommendation_test'),
    path('first-login-guide/', views.first_login_guide, name='first_login_guide'),
] 